Dev to main sprint
CV-goes-frr/CVIP pull request #57
Opened 2024-03-05 12:38 UTC by Maksim-Kotenkov

2024-03-05 13:08 UTC, melarozz requested changes

2024-03-05 13:08 UTC, melarozz commented on src/VerifyQuery.py
> +# print(check("[-i=filename.png]filter[-o=out]filter"))  # should be False
DELETE!!!@!@!@@!

2024-03-05 13:08 UTC, melarozz commented on src/VerifyQuery.py
> +# print(check("[-i=filename .png]filter[-o=out ][out ]filter[-o=out]"))  # should be True but is False!!!
DELETE ALL!!!!!!!!

2024-03-05 13:08 UTC, melarozz commented on src/filters/VideoEditor.py
> +        # self.filter = self.class_map[filter_name]
DELETE!!!

2024-03-05 17:16 UTC, McAninKirill approved these changes
COOOOOOOOOOOL

2024-03-07 02:24 UTC, melarozz approved these changes
nice

2024-03-07 02:25 UTC, merged